### ISSUE TITLE
`0.8` made `Style` `!Sync`; seeking advice

### ISSUE THREAD

**Issue by cyqsimon** [DioxusLabs/taffy#949]
## Description

I was upgrading [`egui_taffy`](https://github.com/PPakalns/egui_taffy) from 0.10 to 0.12 when I ran into this. In this upgrade, they bumped their `taffy` from 0.7.7 to 0.9.2, which included #769 which made a change to an implementation detail of `style::Dimension`. `enum Dimension` is now `struct Dimension`, which cascading several layers deep contains a `*const ()` pointer.

A side-effect (I would guess unintentional) of this change is that it made `Dimension` `!Sync`, which propagated to `Style`. This made it so that it is no longer possible to memoize `Style` using a `static LazyLock`, so that subsequent usage is simply a clone instead of a potentially expensive recomputation.

## To reproduce

```rs
static STYLE: LazyLock<taffy::Style> = LazyLock::new(|| todo!());
```

This compiles in 0.7, but no longer does in 0.8+.

## My questions

- Is this side-effect something you overlooked, or is it something you foresaw and deemed acceptable?
- Would it be possible to make `Style` `Sync` again? If not what do you recommend I do?

## Full compiler output

```
error[E0277]: `*const ()` cannot be shared between threads safely
   --> path/to/my/source.rs:101:34
    |
101 |             static BUTTON_STYLE: LazyLock<Style> = LazyLock::new(|| Style {
    |                                  ^^^^^^^^^^^^^^^ `*const ()` cannot be shared between threads safely
    |
    = help: within `egui_taffy::taffy::Style`, the trait `Sync` is not implemented for `*const ()`
note: required because it appears within the type `egui_taffy::taffy::style::compact_length::inner::CompactLengthInner`
   --> /home/cyq/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/taffy-0.9.2/src/style/compact_length.rs:62:23
    |
 62 |     pub(super) struct CompactLengthInner {
    |                       ^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `CompactLength`
   --> /home/cyq/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/taffy-0.9.2/src/style/compact_length.rs:210:12
    |
210 | pub struct CompactLength(CompactLengthInner);
    |            ^^^^^^^^^^^^^
note: required because it appears within the type `egui_taffy::taffy::Dimension`
   --> /home/cyq/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/taffy-0.9.2/src/style/dimension.rs:199:12
    |
199 | pub struct Dimension(pub(crate) CompactLength);
    |            ^^^^^^^^^
note: required because it appears within the type `egui_taffy::taffy::Style`
   --> /home/cyq/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/taffy-0.9.2/src/style/mod.rs:363:12
    |
363 | pub struct Style<S: CheapCloneStr = DefaultCheapStr> {
    |            ^^^^^
    = note: required for `LazyLock<egui_taffy::taffy::Style>` to implement `Sync`
    = note: shared static variables must have a type that implements `Sync`
```

**Comment by nicoburns** [comment]
> Is this side-effect something you overlooked, or is it something you foresaw and deemed acceptable?

It's unavoidable if we want to expose a sound API, without making everything generic over the `Calc` type (which we want to do in https://github.com/DioxusLabs/taffy/pull/855, but it's a big job).

> If not what do you recommend I do?

I recommend you create a wrapper for `Style` in your app and `unsafe impl Send + Sync` for it. It's safe so long as you are either not using `Calc`, or you calc type implements `Send + Sync` (this will almost always be true, it's just that almost always isn't good enough for a safe library API).

**Comment by cyqsimon** [comment]
Thanks for the swift reply.

> It's unavoidable if we want to expose a sound API, without making everything generic over the `Calc` type (which we want to do in [#855](https://github.com/DioxusLabs/taffy/pull/855), but it's a big job).

So what you are saying is when and if after #855 is merged, it would be possible to make `Style` `Sync` again? Am I understanding you correctly?

> I recommend you create a wrapper for `Style` in your app and `unsafe impl Send + Sync` for it. It's safe so long as you are either not using `Calc`, or you calc type implements `Send + Sync` (this will almost always be true, it's just that almost always isn't good enough for a safe library API).

Yep I understand the logic behind the design choice. What I'll probably end up doing is just delay the upgrade for a while (possibly a good while). And if some particular reason comes about in the future that compels me to upgrade, then I'll adopt your recommendation, if indeed by then there is still no better alternative. Anyway thanks again.
